<section class="w3-theme-l1 w3-padding-32" style="margin-top:64px; width:100%">
    <center>
        <header class="w3-slim w3-padding-top">
            <h4>Aplikace <b>Pobyty In-Life</b></h4>
            <p class="w3-text-dark-grey w3-padding-left w3-padding-right">Pro vstup do systému zadejte uživatelské jméno a heslo.</p>
        </header>
        <section class="w3-margin w3-padding-top w3-slim w3-theme-l1" style="width: 240px;">
            <form method="post">
                <input type="text" name="user" placeholder="Uživatelské jméno" class="w3-margin-top w3-padding w3-border w3-round" style="width:85%;"/><br/>
                <input type="password" name="password" placeholder="Heslo" class="w3-margin-top w3-padding w3-border w3-round" style="width:85%;"/><br/>
                <input type="submit" value="Přihlásit" class="w3-btn w3-dark-grey w3-margin-top w3-margin-bottom w3-round w3-hover-black"/>
            </form>
        </section>
    </center>
</section>